PLATFORM=arm32

MODULES+=stdlib_mini printf barebone_utils_arm32 arm32_aeabi_division apple_uart mmu_arm32 interrupt_arm32 mmu_pte_arm64

SRCROOT=$(TARGETROOT)/src
OBJS=main.o glue.o target.o

include $(BUILDRULES)
